//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CustomerInvoiceEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CustomerInvoiceEntities object using the connection string found in the 'CustomerInvoiceEntities' section of the application configuration file.
        /// </summary>
        public CustomerInvoiceEntities() : base("name=CustomerInvoiceEntities", "CustomerInvoiceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CustomerInvoiceEntities object.
        /// </summary>
        public CustomerInvoiceEntities(string connectionString) : base(connectionString, "CustomerInvoiceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CustomerInvoiceEntities object.
        /// </summary>
        public CustomerInvoiceEntities(EntityConnection connection) : base(connection, "CustomerInvoiceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AccountInfo> AccountInfo
        {
            get
            {
                if ((_AccountInfo == null))
                {
                    _AccountInfo = base.CreateObjectSet<AccountInfo>("AccountInfo");
                }
                return _AccountInfo;
            }
        }
        private ObjectSet<AccountInfo> _AccountInfo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntityNameValue> EntityNameValue
        {
            get
            {
                if ((_EntityNameValue == null))
                {
                    _EntityNameValue = base.CreateObjectSet<EntityNameValue>("EntityNameValue");
                }
                return _EntityNameValue;
            }
        }
        private ObjectSet<EntityNameValue> _EntityNameValue;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Invoice> Invoice
        {
            get
            {
                if ((_Invoice == null))
                {
                    _Invoice = base.CreateObjectSet<Invoice>("Invoice");
                }
                return _Invoice;
            }
        }
        private ObjectSet<Invoice> _Invoice;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InvoiceRemark> InvoiceRemark
        {
            get
            {
                if ((_InvoiceRemark == null))
                {
                    _InvoiceRemark = base.CreateObjectSet<InvoiceRemark>("InvoiceRemark");
                }
                return _InvoiceRemark;
            }
        }
        private ObjectSet<InvoiceRemark> _InvoiceRemark;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MasterMenu> MasterMenu
        {
            get
            {
                if ((_MasterMenu == null))
                {
                    _MasterMenu = base.CreateObjectSet<MasterMenu>("MasterMenu");
                }
                return _MasterMenu;
            }
        }
        private ObjectSet<MasterMenu> _MasterMenu;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ObjectMenu> ObjectMenu
        {
            get
            {
                if ((_ObjectMenu == null))
                {
                    _ObjectMenu = base.CreateObjectSet<ObjectMenu>("ObjectMenu");
                }
                return _ObjectMenu;
            }
        }
        private ObjectSet<ObjectMenu> _ObjectMenu;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PersonMenu> PersonMenu
        {
            get
            {
                if ((_PersonMenu == null))
                {
                    _PersonMenu = base.CreateObjectSet<PersonMenu>("PersonMenu");
                }
                return _PersonMenu;
            }
        }
        private ObjectSet<PersonMenu> _PersonMenu;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReadingLog> ReadingLog
        {
            get
            {
                if ((_ReadingLog == null))
                {
                    _ReadingLog = base.CreateObjectSet<ReadingLog>("ReadingLog");
                }
                return _ReadingLog;
            }
        }
        private ObjectSet<ReadingLog> _ReadingLog;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InvoiceTicket> InvoiceTicket
        {
            get
            {
                if ((_InvoiceTicket == null))
                {
                    _InvoiceTicket = base.CreateObjectSet<InvoiceTicket>("InvoiceTicket");
                }
                return _InvoiceTicket;
            }
        }
        private ObjectSet<InvoiceTicket> _InvoiceTicket;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReadingLogLine> ReadingLogLine
        {
            get
            {
                if ((_ReadingLogLine == null))
                {
                    _ReadingLogLine = base.CreateObjectSet<ReadingLogLine>("ReadingLogLine");
                }
                return _ReadingLogLine;
            }
        }
        private ObjectSet<ReadingLogLine> _ReadingLogLine;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InvoicePassenger> InvoicePassenger
        {
            get
            {
                if ((_InvoicePassenger == null))
                {
                    _InvoicePassenger = base.CreateObjectSet<InvoicePassenger>("InvoicePassenger");
                }
                return _InvoicePassenger;
            }
        }
        private ObjectSet<InvoicePassenger> _InvoicePassenger;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AccountInfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccountInfo(AccountInfo accountInfo)
        {
            base.AddObject("AccountInfo", accountInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EntityNameValue EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntityNameValue(EntityNameValue entityNameValue)
        {
            base.AddObject("EntityNameValue", entityNameValue);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Invoice EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInvoice(Invoice invoice)
        {
            base.AddObject("Invoice", invoice);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InvoiceRemark EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInvoiceRemark(InvoiceRemark invoiceRemark)
        {
            base.AddObject("InvoiceRemark", invoiceRemark);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MasterMenu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMasterMenu(MasterMenu masterMenu)
        {
            base.AddObject("MasterMenu", masterMenu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ObjectMenu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToObjectMenu(ObjectMenu objectMenu)
        {
            base.AddObject("ObjectMenu", objectMenu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PersonMenu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPersonMenu(PersonMenu personMenu)
        {
            base.AddObject("PersonMenu", personMenu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReadingLog EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReadingLog(ReadingLog readingLog)
        {
            base.AddObject("ReadingLog", readingLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InvoiceTicket EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInvoiceTicket(InvoiceTicket invoiceTicket)
        {
            base.AddObject("InvoiceTicket", invoiceTicket);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReadingLogLine EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReadingLogLine(ReadingLogLine readingLogLine)
        {
            base.AddObject("ReadingLogLine", readingLogLine);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InvoicePassenger EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInvoicePassenger(InvoicePassenger invoicePassenger)
        {
            base.AddObject("InvoicePassenger", invoicePassenger);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerInvoiceModel", Name="AccountInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AccountInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AccountInfo object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static AccountInfo CreateAccountInfo(global::System.Guid id)
        {
            AccountInfo accountInfo = new AccountInfo();
            accountInfo.ID = id;
            return accountInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccountCode
        {
            get
            {
                return _AccountCode;
            }
            set
            {
                OnAccountCodeChanging(value);
                ReportPropertyChanging("AccountCode");
                _AccountCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccountCode");
                OnAccountCodeChanged();
            }
        }
        private global::System.String _AccountCode;
        partial void OnAccountCodeChanging(global::System.String value);
        partial void OnAccountCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Detail
        {
            get
            {
                return _Detail;
            }
            set
            {
                OnDetailChanging(value);
                ReportPropertyChanging("Detail");
                _Detail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Detail");
                OnDetailChanged();
            }
        }
        private global::System.String _Detail;
        partial void OnDetailChanging(global::System.String value);
        partial void OnDetailChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerInvoiceModel", Name="EntityNameValue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntityNameValue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntityNameValue object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="entityID">Initial value of the EntityID property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static EntityNameValue CreateEntityNameValue(global::System.Guid id, global::System.Guid entityID, global::System.String value)
        {
            EntityNameValue entityNameValue = new EntityNameValue();
            entityNameValue.ID = id;
            entityNameValue.EntityID = entityID;
            entityNameValue.Value = value;
            return entityNameValue;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid EntityID
        {
            get
            {
                return _EntityID;
            }
            set
            {
                OnEntityIDChanging(value);
                ReportPropertyChanging("EntityID");
                _EntityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntityID");
                OnEntityIDChanged();
            }
        }
        private global::System.Guid _EntityID;
        partial void OnEntityIDChanging(global::System.Guid value);
        partial void OnEntityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsDelete
        {
            get
            {
                return _IsDelete;
            }
            set
            {
                OnIsDeleteChanging(value);
                ReportPropertyChanging("IsDelete");
                _IsDelete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDelete");
                OnIsDeleteChanged();
            }
        }
        private Nullable<global::System.Int32> _IsDelete;
        partial void OnIsDeleteChanging(Nullable<global::System.Int32> value);
        partial void OnIsDeleteChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerInvoiceModel", Name="Invoice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Invoice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Invoice object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Invoice CreateInvoice(global::System.Guid id)
        {
            Invoice invoice = new Invoice();
            invoice.ID = id;
            return invoice;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RecordLocator
        {
            get
            {
                return _RecordLocator;
            }
            set
            {
                OnRecordLocatorChanging(value);
                ReportPropertyChanging("RecordLocator");
                _RecordLocator = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RecordLocator");
                OnRecordLocatorChanged();
            }
        }
        private global::System.String _RecordLocator;
        partial void OnRecordLocatorChanging(global::System.String value);
        partial void OnRecordLocatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InvoiceNumber
        {
            get
            {
                return _InvoiceNumber;
            }
            set
            {
                OnInvoiceNumberChanging(value);
                ReportPropertyChanging("InvoiceNumber");
                _InvoiceNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InvoiceNumber");
                OnInvoiceNumberChanged();
            }
        }
        private global::System.String _InvoiceNumber;
        partial void OnInvoiceNumberChanging(global::System.String value);
        partial void OnInvoiceNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ReadingLogID
        {
            get
            {
                return _ReadingLogID;
            }
            set
            {
                OnReadingLogIDChanging(value);
                ReportPropertyChanging("ReadingLogID");
                _ReadingLogID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReadingLogID");
                OnReadingLogIDChanged();
            }
        }
        private Nullable<global::System.Guid> _ReadingLogID;
        partial void OnReadingLogIDChanging(Nullable<global::System.Guid> value);
        partial void OnReadingLogIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> FareAmount
        {
            get
            {
                return _FareAmount;
            }
            set
            {
                OnFareAmountChanging(value);
                ReportPropertyChanging("FareAmount");
                _FareAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FareAmount");
                OnFareAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _FareAmount;
        partial void OnFareAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnFareAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TaxAmount
        {
            get
            {
                return _TaxAmount;
            }
            set
            {
                OnTaxAmountChanging(value);
                ReportPropertyChanging("TaxAmount");
                _TaxAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TaxAmount");
                OnTaxAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _TaxAmount;
        partial void OnTaxAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnTaxAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalAmount
        {
            get
            {
                return _TotalAmount;
            }
            set
            {
                OnTotalAmountChanging(value);
                ReportPropertyChanging("TotalAmount");
                _TotalAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalAmount");
                OnTotalAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalAmount;
        partial void OnTotalAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Branch
        {
            get
            {
                return _Branch;
            }
            set
            {
                OnBranchChanging(value);
                ReportPropertyChanging("Branch");
                _Branch = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Branch");
                OnBranchChanged();
            }
        }
        private global::System.String _Branch;
        partial void OnBranchChanging(global::System.String value);
        partial void OnBranchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AgentName
        {
            get
            {
                return _AgentName;
            }
            set
            {
                OnAgentNameChanging(value);
                ReportPropertyChanging("AgentName");
                _AgentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AgentName");
                OnAgentNameChanged();
            }
        }
        private global::System.String _AgentName;
        partial void OnAgentNameChanging(global::System.String value);
        partial void OnAgentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccountCode
        {
            get
            {
                return _AccountCode;
            }
            set
            {
                OnAccountCodeChanging(value);
                ReportPropertyChanging("AccountCode");
                _AccountCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccountCode");
                OnAccountCodeChanged();
            }
        }
        private global::System.String _AccountCode;
        partial void OnAccountCodeChanging(global::System.String value);
        partial void OnAccountCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> InvoiceDate
        {
            get
            {
                return _InvoiceDate;
            }
            set
            {
                OnInvoiceDateChanging(value);
                ReportPropertyChanging("InvoiceDate");
                _InvoiceDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvoiceDate");
                OnInvoiceDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _InvoiceDate;
        partial void OnInvoiceDateChanging(Nullable<global::System.DateTime> value);
        partial void OnInvoiceDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerInvoiceModel", Name="InvoicePassenger")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InvoicePassenger : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InvoicePassenger object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static InvoicePassenger CreateInvoicePassenger(global::System.Guid id)
        {
            InvoicePassenger invoicePassenger = new InvoicePassenger();
            invoicePassenger.ID = id;
            return invoicePassenger;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> InvoiceID
        {
            get
            {
                return _InvoiceID;
            }
            set
            {
                OnInvoiceIDChanging(value);
                ReportPropertyChanging("InvoiceID");
                _InvoiceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvoiceID");
                OnInvoiceIDChanged();
            }
        }
        private Nullable<global::System.Guid> _InvoiceID;
        partial void OnInvoiceIDChanging(Nullable<global::System.Guid> value);
        partial void OnInvoiceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PassengerName
        {
            get
            {
                return _PassengerName;
            }
            set
            {
                OnPassengerNameChanging(value);
                ReportPropertyChanging("PassengerName");
                _PassengerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PassengerName");
                OnPassengerNameChanged();
            }
        }
        private global::System.String _PassengerName;
        partial void OnPassengerNameChanging(global::System.String value);
        partial void OnPassengerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private Nullable<global::System.Int32> _Position;
        partial void OnPositionChanging(Nullable<global::System.Int32> value);
        partial void OnPositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ReadingLogID
        {
            get
            {
                return _ReadingLogID;
            }
            set
            {
                OnReadingLogIDChanging(value);
                ReportPropertyChanging("ReadingLogID");
                _ReadingLogID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReadingLogID");
                OnReadingLogIDChanged();
            }
        }
        private Nullable<global::System.Guid> _ReadingLogID;
        partial void OnReadingLogIDChanging(Nullable<global::System.Guid> value);
        partial void OnReadingLogIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerInvoiceModel", Name="InvoiceRemark")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InvoiceRemark : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InvoiceRemark object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static InvoiceRemark CreateInvoiceRemark(global::System.Guid id)
        {
            InvoiceRemark invoiceRemark = new InvoiceRemark();
            invoiceRemark.ID = id;
            return invoiceRemark;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> InvoiceID
        {
            get
            {
                return _InvoiceID;
            }
            set
            {
                OnInvoiceIDChanging(value);
                ReportPropertyChanging("InvoiceID");
                _InvoiceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvoiceID");
                OnInvoiceIDChanged();
            }
        }
        private Nullable<global::System.Guid> _InvoiceID;
        partial void OnInvoiceIDChanging(Nullable<global::System.Guid> value);
        partial void OnInvoiceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerInvoiceModel", Name="InvoiceTicket")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InvoiceTicket : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InvoiceTicket object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static InvoiceTicket CreateInvoiceTicket(global::System.Guid id)
        {
            InvoiceTicket invoiceTicket = new InvoiceTicket();
            invoiceTicket.ID = id;
            return invoiceTicket;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> InvoiceID
        {
            get
            {
                return _InvoiceID;
            }
            set
            {
                OnInvoiceIDChanging(value);
                ReportPropertyChanging("InvoiceID");
                _InvoiceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvoiceID");
                OnInvoiceIDChanged();
            }
        }
        private Nullable<global::System.Guid> _InvoiceID;
        partial void OnInvoiceIDChanging(Nullable<global::System.Guid> value);
        partial void OnInvoiceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TicketNumber
        {
            get
            {
                return _TicketNumber;
            }
            set
            {
                OnTicketNumberChanging(value);
                ReportPropertyChanging("TicketNumber");
                _TicketNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TicketNumber");
                OnTicketNumberChanged();
            }
        }
        private global::System.String _TicketNumber;
        partial void OnTicketNumberChanging(global::System.String value);
        partial void OnTicketNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PassengerName
        {
            get
            {
                return _PassengerName;
            }
            set
            {
                OnPassengerNameChanging(value);
                ReportPropertyChanging("PassengerName");
                _PassengerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PassengerName");
                OnPassengerNameChanged();
            }
        }
        private global::System.String _PassengerName;
        partial void OnPassengerNameChanging(global::System.String value);
        partial void OnPassengerNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerInvoiceModel", Name="MasterMenu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MasterMenu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MasterMenu object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static MasterMenu CreateMasterMenu(global::System.Guid id)
        {
            MasterMenu masterMenu = new MasterMenu();
            masterMenu.ID = id;
            return masterMenu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsDelete
        {
            get
            {
                return _IsDelete;
            }
            set
            {
                OnIsDeleteChanging(value);
                ReportPropertyChanging("IsDelete");
                _IsDelete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDelete");
                OnIsDeleteChanged();
            }
        }
        private Nullable<global::System.Int32> _IsDelete;
        partial void OnIsDeleteChanging(Nullable<global::System.Int32> value);
        partial void OnIsDeleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreatorID
        {
            get
            {
                return _CreatorID;
            }
            set
            {
                OnCreatorIDChanging(value);
                ReportPropertyChanging("CreatorID");
                _CreatorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatorID");
                OnCreatorIDChanged();
            }
        }
        private Nullable<global::System.Guid> _CreatorID;
        partial void OnCreatorIDChanging(Nullable<global::System.Guid> value);
        partial void OnCreatorIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerInvoiceModel", Name="ObjectMenu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ObjectMenu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ObjectMenu object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static ObjectMenu CreateObjectMenu(global::System.Guid id)
        {
            ObjectMenu objectMenu = new ObjectMenu();
            objectMenu.ID = id;
            return objectMenu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsDelete
        {
            get
            {
                return _IsDelete;
            }
            set
            {
                OnIsDeleteChanging(value);
                ReportPropertyChanging("IsDelete");
                _IsDelete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDelete");
                OnIsDeleteChanged();
            }
        }
        private Nullable<global::System.Int32> _IsDelete;
        partial void OnIsDeleteChanging(Nullable<global::System.Int32> value);
        partial void OnIsDeleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreatorID
        {
            get
            {
                return _CreatorID;
            }
            set
            {
                OnCreatorIDChanging(value);
                ReportPropertyChanging("CreatorID");
                _CreatorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatorID");
                OnCreatorIDChanged();
            }
        }
        private Nullable<global::System.Guid> _CreatorID;
        partial void OnCreatorIDChanging(Nullable<global::System.Guid> value);
        partial void OnCreatorIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerInvoiceModel", Name="PersonMenu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PersonMenu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PersonMenu object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static PersonMenu CreatePersonMenu(global::System.Guid id)
        {
            PersonMenu personMenu = new PersonMenu();
            personMenu.ID = id;
            return personMenu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsDelete
        {
            get
            {
                return _IsDelete;
            }
            set
            {
                OnIsDeleteChanging(value);
                ReportPropertyChanging("IsDelete");
                _IsDelete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDelete");
                OnIsDeleteChanged();
            }
        }
        private Nullable<global::System.Int32> _IsDelete;
        partial void OnIsDeleteChanging(Nullable<global::System.Int32> value);
        partial void OnIsDeleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CreatorID
        {
            get
            {
                return _CreatorID;
            }
            set
            {
                OnCreatorIDChanging(value);
                ReportPropertyChanging("CreatorID");
                _CreatorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatorID");
                OnCreatorIDChanged();
            }
        }
        private Nullable<global::System.Guid> _CreatorID;
        partial void OnCreatorIDChanging(Nullable<global::System.Guid> value);
        partial void OnCreatorIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerInvoiceModel", Name="ReadingLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReadingLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReadingLog object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="readingDate">Initial value of the ReadingDate property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        public static ReadingLog CreateReadingLog(global::System.Guid id, global::System.DateTime readingDate, global::System.String fileName)
        {
            ReadingLog readingLog = new ReadingLog();
            readingLog.ID = id;
            readingLog.ReadingDate = readingDate;
            readingLog.FileName = fileName;
            return readingLog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ReadingDate
        {
            get
            {
                return _ReadingDate;
            }
            set
            {
                OnReadingDateChanging(value);
                ReportPropertyChanging("ReadingDate");
                _ReadingDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReadingDate");
                OnReadingDateChanged();
            }
        }
        private global::System.DateTime _ReadingDate;
        partial void OnReadingDateChanging(global::System.DateTime value);
        partial void OnReadingDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FileCreateDate
        {
            get
            {
                return _FileCreateDate;
            }
            set
            {
                OnFileCreateDateChanging(value);
                ReportPropertyChanging("FileCreateDate");
                _FileCreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FileCreateDate");
                OnFileCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _FileCreateDate;
        partial void OnFileCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnFileCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FileModifyDate
        {
            get
            {
                return _FileModifyDate;
            }
            set
            {
                OnFileModifyDateChanging(value);
                ReportPropertyChanging("FileModifyDate");
                _FileModifyDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FileModifyDate");
                OnFileModifyDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _FileModifyDate;
        partial void OnFileModifyDateChanging(Nullable<global::System.DateTime> value);
        partial void OnFileModifyDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomerInvoiceModel", Name="ReadingLogLine")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReadingLogLine : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReadingLogLine object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static ReadingLogLine CreateReadingLogLine(global::System.Guid id)
        {
            ReadingLogLine readingLogLine = new ReadingLogLine();
            readingLogLine.ID = id;
            return readingLogLine;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ReadingLogID
        {
            get
            {
                return _ReadingLogID;
            }
            set
            {
                OnReadingLogIDChanging(value);
                ReportPropertyChanging("ReadingLogID");
                _ReadingLogID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReadingLogID");
                OnReadingLogIDChanged();
            }
        }
        private Nullable<global::System.Guid> _ReadingLogID;
        partial void OnReadingLogIDChanging(Nullable<global::System.Guid> value);
        partial void OnReadingLogIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Index
        {
            get
            {
                return _Index;
            }
            set
            {
                OnIndexChanging(value);
                ReportPropertyChanging("Index");
                _Index = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Index");
                OnIndexChanged();
            }
        }
        private Nullable<global::System.Int32> _Index;
        partial void OnIndexChanging(Nullable<global::System.Int32> value);
        partial void OnIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Line
        {
            get
            {
                return _Line;
            }
            set
            {
                OnLineChanging(value);
                ReportPropertyChanging("Line");
                _Line = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Line");
                OnLineChanged();
            }
        }
        private global::System.String _Line;
        partial void OnLineChanging(global::System.String value);
        partial void OnLineChanged();

        #endregion
    
    }

    #endregion
    
}
